### ISSUE TITLE
No way to get random access of known keys from unknown sections while iterating

### ISSUE THREAD

**Issue by dralley** [pinecrew/tini#35]
Hello, I have been struggling to find a way to easily parse a known (sub)set of keys from an unknown list of section names.  It is possible but not very easy to do, due to an unfortunate limitation of the current API.

```ini
[rhel7]
metadata_expire = 86400
enabled_metadata = 0
sslclientcert = /etc/pki/entitlement/9348759348759374.pem
baseurl = https://cdn.redhat.com/content/dist/rhel/server/7/7Server/$basearch/
sslverify = 1
name = RHEL 7
sslclientkey = /etc/pki/entitlement/9348759348759374-key.pem
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
enabled = 0
sslcacert = /etc/rhsm/ca/redhat-uep.pem
gpgcheck = 1
```

And here's my code:

```rust
for (name, section) in repo_file.iter() {
    let mut config = DownloadConfig::new();

    for (key, value) in section {
        match key.as_str() {
            "sslclientkey" => println!("sslclientkey => {}", value),
            "sslclientcert" => println!("sslclientcert => {}", value),
            "sslcacert" => config = config.with_ca_cert(value),
            "sslverify" => config = config.verify_tls(value.parse()?),
            _ => (),
        }
    }
}
```

The problem is that the `Iterator` impl for `Ini` uses `SectionIter` as an item type rather than `Section`.  This means that there's no way to just get keys from the section, one would need to either iterate over the keys and collect them into a totally new map, or ignore the `SectionIter` and iterating the section names, while using `config.get("...", "...")`.  Which would work... but neither of these are very idiomatic ways to work with the API.

The problem with the match approach described in the docs is that it's inflexible.  What I wrote above doesn't actually work because I need to provide the value of both `sslclientkey` and `sslclientcert` at once to the same function call.  So now I would need to keep parsing state outside of the loop.

It would be substantially easier if I could iterate over `Section`, and if I wanted the `SectionIter` behavior to just call `section.iter()` and iterate over that.  e.g.

```rust
for (name, section) in repo_file.iter() {
    let mut config = DownloadConfig::new();

    // section handle allows random access to keys, just like Ini::get()
    if let Some(sslclientcert) = section.get("sslclientcert") {
        let client_key = section.get("sslclientkey").unwrap_or(sslclientcert);
        config = config.with_client_certificate(client_cert, client_key);
    }

    // note ".iter()"
    for (key, value) in section.iter() {
        match key.as_str() {
            "sslcacert" => config = config.with_ca_cert(value),
            "sslverify" => config = config.verify_tls(value.parse()?),
            _ => (),
        }
    }
}
```

**Comment by dralley** [comment]
By the way, I don't want to sound too critical because this otherwise seems like the best of the Rust "ini" parsing libraries!  Thank you for your work.

**Comment by dralley** [comment]
Unfortunately I think changing this would require a major version bump.  If that's something that you are open to, I have a few other suggested improvements as well.

**Comment by FreeCX** [comment]
Hello @dralley.

> I don't want to sound too critical because this otherwise seems like the best of the Rust "ini" parsing libraries! 

Thanks!

> I think changing this would require a major version bump.

I think I have a solution without increasing major version, but it needs to be discussed with @citrux.

> I have a few other suggested improvements as well.

Feel free to open new issue or PR and we will consider it in our free time.

**Comment by dralley** [comment]
Hey @FreeCX , I see that there are a few issues slated for "2.0", do you think it would make sense to revisit the design here?

I'm definitely glad that it's possible to do now but the original (API breaking) proposal still seems more consistent and ergonomic.

**Comment by FreeCX** [comment]
Hi @dralley.

>  I see that there are a few issues slated for "2.0", do you think it would make sense to revisit the design here?
Yes, why not.

As for version 2.0 - I don't know when we will have time to do it.
