### ISSUE TITLE
Parsing error with # comment

### ISSUE THREAD

**Issue by 1sra3l** [pinecrew/tini#37]
I love this lib, please make `#` comments not cause a parsing error!!!
In POSIX environments # is the standard comment.  I want to use your library for parsing XDG ini style files.
It works so well except for this one bug!

**Comment by FreeCX** [comment]
Hello @1sra3l .
Thanks for using our library!
In the next couple of days we will consider the possibility of choosing a symbol for the comment.

**Comment by 1sra3l** [comment]
I know another common one is the `;` symbol.  AFAIK the `#` is more common, however
