### ISSUE TITLE
Filename inside ini struct

### ISSUE THREAD

**Issue by 1sra3l** [pinecrew/tini#41]
Your code is really straight forward and easy to use great work!
Would it be a trouble to add a filename to the Ini struct?
My thinking is that I could pass the string of the file in with the filename, rather than doing multiple disk read operations.
Storing the filename could be something like
```rs
   #[derive(Debug)]
pub struct Ini {
    #[doc(hidden)]
    document: OrderedHashMap<String, Section>,
    file_name: String,
    last_section_name: String,
    empty_section: Section,
}
// snip.... though `new` would need file_name: String::new()
 pub fn from_file<S>(path: &S) -> Result<Ini, Error>
    where
        S: AsRef<Path> + ?Sized,
    {
        let file = File::open(path)?;
        let mut reader = BufReader::new(file);
        let mut result = Ini::from_reader(&mut reader)
        result.file_name = match path.to_str() {
            Some(path) => path,
            None => String::new(),
        };
    }
```
I haven't dug fully into your library, since it works so well I haven't needed to :smile: , but there may be other areas this change could effect.

**Comment by FreeCX** [comment]
Hello @1sra3l.
We need to think about this change.

**Comment by citrux** [comment]
Hi, @1sra3l! We think storing file name in Ini struct is unnecessary. You can use `from_reader` or `from_string` and store it in your code as additional variable. Also, you can use (String, Ini) type for it or your own structure.

Thank you for your advice! We appreciate it! 🙏

**Comment by 1sra3l** [comment]
I am storing it, thanks for the consideration.  Rust is nice that you can easily wrap nearly anything you want to.  Thanks!
