### ISSUE TITLE
get_vec_with_sep() fails to get more than first element with ";"

### ISSUE THREAD

**Issue by 1sra3l** [pinecrew/tini#43]
Hi, I think this is an issue in Rust itself, but not sure where to go...

```rust
const TEST_DESKTOP_FILE:&str = r#"[Desktop Entry]
Name=Test
Name[en_US]=Test
Name[en_GB]=Test
Name[en]=Test
GenericName=Generic Test
Comment=A general test desktop file
Icon=text-editor
Exec=ls -lah
Terminal=true
Type=Application
Categories=Utility;Core;System"#;
use tini::Ini;
let conf = Ini::from_string(TEST_DESKTOP_FILE).unwrap();
let result:Option<Vec<String>> = conf.get_vec_with_sep("Desktop Entry", "Categories", ";");
// FAILS :(
assert_eq!(result, Some(vec![
                                "Utility",
                                "Core",
                                "System",
                                ]));
```
It only returns `Some(["Utility"]);`

```rust
// manual test
let res:Option<String> = conf.get("Desktop Entry", "Categories");
let res = res.unwrap();
let mut split = res.split(";");
let result:Vec<&str> = split.collect();
// ALSO FAILS :(
assert_eq!(result, vec![
                                "Utility",
                                "Core",
                                "System",
                                ]);
```
If I change the ";" to a "," it works....
So I think this is not a **tini** specific case, but who do I ask to fix this bug I found using your library?

**Comment by FreeCX** [comment]
Hi @1sra3l.

We use `;` and `#` characters for comments.

In version 2.0, this problem will be resolved. But it's not clear yet when we'll do it.

**Comment by 1sra3l** [comment]
@FreeCX thanks I see now why the second one fails is the comment issue, not a rust issue.
Thanks for addressing it!
Is there a workaround I can use for the time being?

**Comment by FreeCX** [comment]
You can fork and change comment symbol
https://github.com/pinecrew/tini/blob/master/src/parser.rs#L20

**Comment by 1sra3l** [comment]
@FreeCX You rock!  Thanks so much for getting back so quickly and helping so completely!
